specVersion: 0.0.1
description: GraphQL service for Uniques and Assets on Statemine
repository: https://github.com/vikiival/unique.git
schema: ./schema.graphql
network:
  endpoint: wss://pub.elara.patract.io/statemine
definitions:
  mapping: &mymapping
    handlers:
      - handler: handleEventMaster
        kind: substrate/EventHandler
        filter:
          module: uniques
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 323750
    mapping: *mymapping # can reuse or change